//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public int mark_id { get; set; }
        public double ball { get; set; }
        public int subject_id { get; set; }
        public int list_id { get; set; }
    
        public virtual Statement Statement { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
