//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reward
    {
        public int reward_id { get; set; }
        public string title { get; set; }
        public string level { get; set; }
        public int value { get; set; }
        public int event_id { get; set; }
        public Nullable<int> list_id { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual List List { get; set; }
    }
}
